config/routes.rb
Rails.application.routes.draw do

  resources :locations
  get 'map' => 'locations#index2'
   get 'article/list' => 'article#list'

  get 'article/application' => 'article#application'
  get 'article/araapplication' => 'article#araapplication'
  get "article/new" => "article#new"

  get "article/pdf" => "article#pdf"
  post "article/pdf" => "article#pdf"
  get "article/arbeiterlaubnis" => "article#arbeiterlaubnis"
  resources :articles

  root 'welcome#index'

    get "articles/index" => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base 


end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 #protect_from_forgery with: :exception
 before_filter :set_locale

  before_action :set_locale

	def default_url_options(options = {})
	  { locale: I18n.locale }.merge options
	end

	def set_locale
	  I18n.locale = params[:locale] || I18n.default_locale
	end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def list
    #here i will list all my articles


    @ArticleTitle = "Trump ends wild day on campaign trail by calling for protesters' arrests"
    @ArticleAuthor = 'Jeremy Diamond '
    @ArticleDate = "13th December 2016"
    @ArticleDescription = "(CNN)Donald Trump on Saturday called for protesters who disrupt his rallies to be arrested, one day after altercations and protests forced him to cancel a campaign rally in Chicago."

    @ArticleTitle1 = "1- Trump ends wild day on campaign trail by calling for protesters' arrests"
    @ArticleAuthor1 = '1-Jeremy Diamond '
    @ArticleDate1 = "1- 13th December 2016"
    @ArticleDescription1 = "1- (CNN)Donald Trump on Saturday called for protesters who disrupt his rallies to be arrested, one day after altercations and protests forced him to cancel a campaign rally in Chicago."

    @ArticleTitle2 = "2- Trump ends wild day on campaign trail by calling for protesters' arrests"
    @ArticleAuthor2 = '2-Jeremy Diamond '
    @ArticleDate2 = "2- 13th December 2016"
    @ArticleDescription2 = "2- (CNN)Donald Trump on Saturday called for protesters who disrupt his rallies to be arrested, one day after altercations and protests forced him to cancel a campaign rally in Chicago."

    @ArticleTitle3 = "3- Trump ends wild day on campaign trail by calling for protesters' arrests"
    @ArticleAuthor3 = '3-Jeremy Diamond '
    @ArticleDate3 = "3- 13th December 2016"
    @ArticleDescription3 = "3- (CNN)Donald Trump on Saturday called for protesters who disrupt his rallies to be arrested, one day after altercations and protests forced him to cancel a campaign rally in Chicago."

    @list = [
      [@ArticleTitle, @ArticleAuthor, @ArticleDate, @ArticleDescription] ,
      [@ArticleTitle1, @ArticleAuthor1, @ArticleDate1, @ArticleDescription1],
      [@ArticleTitle2, @ArticleAuthor2, @ArticleDate2, @ArticleDescription2],
      [@ArticleTitle3, @ArticleAuthor3, @ArticleDate3, @ArticleDescription3],
    ]

    #render :action => 'list'
   end

   def application
     @surname = params[:surname]
     @firstname= params[:firstname]
     @birthdate =  params[:date_birth]

   end
   def araapplication

   end
   def arbeiterlaubnis

   end

   def arbriterlaubnis

  end

   def pdf
     @surname = params[:surname]
     @firstname= params[:firstname]
     @date_of_birth=  params[:date_of_birth]
     @move_in_date=params[:move_in_date]
     @new_address=params[:new_address]
     @new_postal_code=params[:new_postal_code].to_s
     @old_address=params[:old_address]
     @old_postal_code=params[:old_postal_code]
     @nationality= params[:nationality]
     @religion= params[:religion]
     @marital_status= params[:marital_status]
     @date_of_marriage= params[:date_of_marriage]
     @serial_number= params[:serial_number]
     @place_of_issue= params[:place_of_issue]
     @date_of_issue= params[:date_of_issue]
     @expired_date= params[:expired_date]
     @serial_number_pass= params[:serial_number_pass]
     @place_of_issue_pass= params[:place_of_issue_pass]
     @date_of_issue_pass= params[:date_of_issue_pass]
     @expired_date_pass= params[:expired_date_pass]
   end

   def show
     # here i will see my article detail page
   end

   def new
    @article = Article.new

     # here i create a new article and to save the date base
   end

   def edit
     # here i will update all properties of my article
   end

   def delete
     # here i will delete one article
   end

end

app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
	def contactus

	end
end		

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index2
    @locations = Location.all

  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to action: "index2" , notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to action: "index2", notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :lat, :long)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
  def show
    @text_to_show = params[:id]

  end
  def delete

  end

end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article/application.html.erb
<form action="pdf" method="post">

  <%= t("MoveInDate") %>
  <input type="Date" name="movegin_date">
  <br>

  <%= t("NewAddress") %>
  <input type="text" name="new_address">
<br>

<%= t("NewPostalCode") %>
<input type="text" name="new_postal_code">
<br>

<%= t("oldaddress") %>
<input type="text" name="old_address">
<br>

<%= t("Oldpostalcode") %>
<input type="text" name="Old_postal_code">
<br>


* surname:
<input type="text" name="surname" required>
<br>
* firstame:
<input type="text" name="firstname" required>
<br>

Date of Birth:
<input type="date" name="date_birth" required>
<br>

Nationality:
<input type="text" name="nationality">
<br>

Religion:
<input type="text" name="religiony">
<br>

Marital Status:
<input type="text" name="Marital_Status">
<br>

Date of Marriage:
<input type="Date" name="Date_of_Marriage">
<br>


ID Nr:
<input type="text" name="id_nr">
<br>


Sirial Number(ID):
<input type="text" name="Sirial_number">
<br>


Place of Issue(ID):
<input type="text" name="Place_issue">
<br>



Date of Issue(ID):
<input type="Date" name="Date_issue">
<br>

Expired Date(ID):
<input type="Date" name="expired_Date">
<br>

Sirial Number(passport):
<input type="text" name="Sirial_number">
<br>


Place of Issue(passport):
<input type="text" name="Place_issue">
<br>



Date of Issue(passport):
<input type="Date" name="Date_issue">
<br>

Expired Date(passport):
<input type="Date" name="expired_Date">
<br>

save:
<input type="submit" value="Convert to PDF">
<br>



</form>

app/views/article/araapplication.html.erb
<div class="container">
    <form action="/article/pdf" method="POST" class="form-horizontal">
        <div class="form-group">
            <label for="move_in_date" class="col-sm-2 control-label"><%= t("MoveInDate") %></label>
            <div class="col-sm-3">
                <input type="date" name="move_in_date" id="move_in_date" class="form-control" placeholder="DD/MM/YY"required>
            </div>
        </div>
        <div class="form-group">
            <label for="new_address" class="col-sm-2 control-label"><%= t("NewAddress") %></label>
            <div class="col-sm-3">
                <input type="text" name="new_address" id="new_address" class="form-control" placeholder=""required>
            </div>
        </div>
        <div class="form-group">
            <label for="new_postal_code" class="col-sm-2 control-label"><%= t("NewPostalCode") %></label>
            <div class="col-sm-3">
                <input type="text" name="new_postal_code" id="new_postal_code" class="form-control" placeholder=""required>
            </div>
        </div>
        <div class="form-group">
            <label for="old_postal_code" class="col-sm-2 control-label"><%= t("Oldpostalcode") %></label>
            <div class="col-sm-3">
                <input type="text" name="old_postal_code" id="old_postal_code" class="form-control" placeholder=""required>
            </div>
        </div>
       <div class="form-group">
            <label for="old_address" class="col-sm-2 control-label"><%= t("oldaddress") %></label>
            <div class="col-sm-3">
                <input type="text" name="old_address" id="old_address" class="form-control" placeholder="" required>
            </div>
        </div>
        <div class="form-group">
            <label for="surname" class="col-sm-2 control-label"><%= t("surname") %></label>
            <div class="col-sm-3">
                <input type="text" name="surname" id="surname" class="form-control" placeholder="" required>
            </div>
        </div>
     <div class="form-group">
            <label for="firstname" class="col-sm-2 control-label"><%= t("firstname") %></label>
            <div class="col-sm-3">
                <input type="text" name="firstname" id="firstname" class="form-control" placeholder="" required>
            </div>
        </div>
     <div class="form-group">
            <label for="date_of_birth" class="col-sm-2 control-label"><%= t("datebirth") %></label>
            <div class="col-sm-3">
                <input type="text" name="date_of_birth" id="date_of_birth" class="form-control" placeholder="DD/MM/YY" required>
            </div>
        </div>
     <div class="form-group">
            <label for="nationality" class="col-sm-2 control-label"><%= t("nationality") %></label>
            <div class="col-sm-3">
                <input type="text" name="nationality" id="nationality" class="form-control" placeholder="" required>
            </div>
        </div>
     <div class="form-group">
            <label for="religion" class="col-sm-2 control-label"><%= t("Religion") %></label>
            <div class="col-sm-3">
                <input type="text" name="religion" id="religion" class="form-control" placeholder="" required>
            </div>
        </div>
      <div class="form-group">
            <label for="marital_status" class="col-sm-2 control-label"><%= t("MaritalStatus") %></label>
            <div class="col-sm-3">
                <input type="text" name="marital_status" id="marital_status" class="form-control" placeholder="" required>
            </div>
        </div>
       <div class="form-group">
            <label for="date_of_marriage" class="col-sm-2 control-label"><%= t("DateofMarriage") %></label>
            <div class="col-sm-3">
                <input type="text" name="date_of_marriage" id="date_of_marriage" class="form-control" placeholder="DD/MM/YY" required>
            </div>
        </div>
     <div class="form-group">
            <label for="serial_number" class="col-sm-2 control-label"><%= t("Sirialnumber") %></label>
            <div class="col-sm-3">
                <input type="text" name="serial_number" id="serial_number" class="form-control" placeholder="" required>
            </div>
        </div>
      <div class="form-group">
            <label for="place_of_issue" class="col-sm-2 control-label"><%= t("Placeissue") %></label>
            <div class="col-sm-3">
                <input type="text" name="place_of_issue" id="place_of_issue" class="form-control" placeholder="" required>
            </div>
        </div>
      <div class="form-group">
            <label for="date_of_issue" class="col-sm-2 control-label"><%= t("Dateissue") %></label>
            <div class="col-sm-3">
                <input type="text" name="date_of_issue" id="date_of_issue" class="form-control" placeholder="DD/MM/YY" required>
            </div>
        </div>
      <div class="form-group">
            <label for="expired_date" class="col-sm-2 control-label"><%= t("expiredDate") %></label>
            <div class="col-sm-3">
                <input type="text" name="expired_date" id="expired_date" class="form-control" placeholder="DD/MM/YY" required>
            </div>
        </div>
       <div class="form-group">
            <label for="serial_number_pass" class="col-sm-2 control-label"><%= t("Sirialnumberpassport") %></label>
            <div class="col-sm-3">
                <input type="text" name="serial_number_pass" id="serial_number_pass" class="form-control" placeholder="" required>
            </div>
        </div>
      <div class="form-group">
            <label for="place_of_issue_pass" class="col-sm-2 control-label"><%= t("Placeissue") %></label>
            <div class="col-sm-3">
                <input type="text" name="place_of_issue_pass" id="place_of_issue_pass" class="form-control" placeholder="" required>
            </div>
        </div>
       <div class="form-group">
            <label for="date_of_issue_pass" class="col-sm-2 control-label"><%= t("Dateissue") %></label>
            <div class="col-sm-3">
                <input type="text" name="date_of_issue_pass" id="date_of_issue_pass" class="form-control" placeholder="DD/MM/YY" required>
            </div>
        </div>
       <div class="form-group">
            <label for="expired_date_pass" class="col-sm-2 control-label"><%= t("expiredDatepassport") %></label>
            <div class="col-sm-3">
                <input type="text" name="expired_date_pass" id="expired_date_pass" class="form-control" placeholder="DD/MM/YY" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
               save:
               <input type="submit" value="Convert to PDF" class="btn btn-primary">
           </div>
       </div>
    </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap.min.css' %>
  <%= stylesheet_link_tag 'ie10-viewport-bug-workaround.css' %>
  <%= stylesheet_link_tag 'cover.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <!-- to be fixed!!!! -->


        
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Bureacrazy</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="<%= root_url %>"><%= t("Home") %></a></li>
                  <li><a href="<%= article_araapplication_url %>"><%= t("Applications") %></a></li>
                  <li><a href="#"><%= t("Signin") %></a></li>
                  <li><a href="<%= map_url %>"><%= t("Maps") %></a></li>
                  <li><a href="#"><%= t("ContactUs") %></a></li>
        			     <li>
                      <div class="dropdown">
                        <a href="#" class="dropbtn">Language</a>
                        <div class="dropdown-content">
                          <%= link_to_unless_current "English", locale: "en" %>
                          <%= link_to_unless_current "Arabic", locale: "ar" %>
                          <%= link_to_unless_current "Deutsch", locale: "de" %>
                        </div>
                      </div>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>

          

<!-- Here is the rails way to include content -->

  <%= yield %>


          

          <div class="mastfoot">
            <div class="inner">
              <p>#Group 6  ,<a href="redi-school.org"> ReDI school of digital integration</a></p>
            </div>
          </div>

        </div>

      </div>




</body>
</html>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Listing Locations</h1>
  <div class="row">
    <div class="col-sm-9">
      <div id="map"></div>
    </div>
    <div class="col-sm-3">
      <div class="locations" >
        <ul>
          <% @locations.each do |location| %>
          <li>
            <a href="#" onclick="javascipt:map.panTo({lat: <%= location.lat %>, lng: <%= location.long %>}); map.setZoom(16)"><%= location.name %></a> |
            <%= link_to 'Edit', edit_location_path(location) %> |
            <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
          <% end %>
        </ul>
        <%= link_to 'New Location', new_location_path %>
      </div>

    </div>
  </div>
</div>

  <script type="text/javascript">

    var directionsDisplay;
    var directionsService;
    var map;

    function initMap() {

      map = new google.maps.Map(document.getElementById('map'), {
         center: {lat: 52.5060713, lng: 13.3962265},
         zoom: 11
      });

      <% @locations.each do |location| %>
        new google.maps.Marker({
            map: map,
            position: {lat: <%= location.lat %>, lng: <%= location.long %>},
            title: '<%= location.name %>' });
      <% end %>



     navigator.geolocation.getCurrentPosition(calcRoute);



    function calcRoute(position) {

      directionsDisplay = new google.maps.DirectionsRenderer();
      directionsService = new google.maps.DirectionsService();

      var start = {lat: position.coords.latitude, lng: position.coords.longitude};
      var end = {lat: 52.5376581, lng: 13.3496172};
      var request = {
        origin:start,
        destination:end,
        travelMode: google.maps.TravelMode.DRIVING
      };

      directionsDisplay.setMap(map);

      directionsService.route(request, function(result, status) {
        //console.log(directionsDisplay);
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(result);
        }
      });
    }
  }
  </script>

   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_viYAPxX0PcTdcTS6ep58Ot9ZtgYsqNU&callback=initMap"
   async defer></script>

</body>
</html>

app/views/locations/index2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Displaying text directions with <code>setPanel()</code></title>
    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #floating-panel {
        position: absolute;
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        color: #333;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }
      #right-panel {
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }

      #right-panel select, #right-panel input {
        font-size: 15px;
      }

      #right-panel select {
        width: 100%;
      }

      #right-panel i {
        font-size: 12px;
      }
      #right-panel {
        height: 100%;
        float: right;
        width: 390px;
        overflow: auto;
      }
      #floating-panel {
        background: #fff;
        padding: 5px;
        font-size: 14px;
        font-family: Arial;
        border: 1px solid #ccc;
        box-shadow: 0 2px 2px rgba(33, 33, 33, 0.4);
        display: none;
      }
       .locations {
          width: 100%;
          height: 500px;
          background-color: rgba(255,255,255,.5);
          padding: 20px;
          overflow: auto;
          text-align: left;
        }
        #map {
          height: 500px;
          width: 100%;
          margin: 0;
        }

      @media print {

        #right-panel {
          float: none;
          width: auto;
        }
      }
    </style>
  </head>
  <body>
    <div id="floating-panel">
      <b>Mode of Travel: </b>
    <select id="mode">
      <option value="DRIVING">Driving</option>
      <option value="WALKING">Walking</option>
      <option value="BICYCLING">Bicycling</option>
      <option value="TRANSIT">Transit</option>
    </select>
    <br>
      <strong>End:</strong>
      <select id="end">
        <% @locations.each do |location| %>
           <option value='{"lat": <%= location.lat %>, "lng": <%= location.long %>}'>
            <%= location.name %></option>
        <% end %>
      </select>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div id="map"></div>
        </div>
        <div class="col-sm-3">
          <div class="locations" >
            <ul>
            <% @locations.each do |location| %>
            <li>
            <a href="#" onclick="javascipt:map.panTo({lat: <%= location.lat %>, lng: <%= location.long %>}); map.setZoom(16)"><%= location.name %></a> |
            <%= link_to 'Edit', edit_location_path(location) %> |
            <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %>
            </li>
            <% end %>
            </ul>
            <%= link_to 'New Location', new_location_path %>
          </div>

        </div>
      </div>
    </div>
    <script>
      var map;
      var directionsDisplay;
      var directionsService;
      function initMap() {
        directionsDisplay = new google.maps.DirectionsRenderer;
        directionsService = new google.maps.DirectionsService;
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: {lat:  52.5060713, lng: 13.3962265}
        });
        <% @locations.each do |location| %>
          new google.maps.Marker({
              map: map,
              position: {lat: <%= location.lat %>, lng: <%= location.long %>},
              title: '<%= location.name %>' });
        <% end %>

        directionsDisplay.setMap(map);
        directionsDisplay.setPanel(document.getElementById('right-panel'));

        var control = document.getElementById('floating-panel');
        control.style.display = 'block';
        map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);

        var onChangeHandler = function() {
          calculateAndDisplayRoute(directionsService, directionsDisplay);
          document.getElementById('mode').addEventListener('change', function() {
          calculateAndDisplayRoute(directionsService, directionsDisplay);
        });
      }
        document.getElementById('end').addEventListener('change', onChangeHandler);
      }

      function calculateAndDisplayRoute(directionsService, directionsDisplay) {

        var endEl = document.getElementById("end");
        var end = endEl.options[endEl.selectedIndex].value;

  var start = navigator.geolocation.getCurrentPosition(function(position){
            start = {lat: position.coords.latitude, lng: position.coords.longitude};
            showRoute(start, JSON.parse(end));
          });
      }

      function showRoute(start, end){
        var selectedMode = document.getElementById('mode').value;
        directionsService.route({
          origin: start,
          destination: end,
          travelMode: google.maps.TravelMode[selectedMode]

        }, function(response, status) {
          if (status === google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_viYAPxX0PcTdcTS6ep58Ot9ZtgYsqNU&callback=initMap"
    async defer></script>

  </body>
</html>

app/views/locations/index4.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Listing Locations</h1>
  <div class="row">
    <div class="col-sm-9">
      <div id="map"></div>
    </div>
    <div class="col-sm-3">
      <div class="locations" >
        <ul>
          <% @locations.each do |location| %>
          <li>
            <a href="#" onclick="javascipt:map.panTo({lat: <%= location.lat %>, lng: <%= location.long %>}); map.setZoom(16)"><%= location.name %></a> |
            <%= link_to 'Edit', edit_location_path(location) %> |
            <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
          <% end %>
        </ul>
        <%= link_to 'New Location', new_location_path %>
      </div>

    </div>
  </div>
</div>

  <script type="text/javascript">

    var directionsDisplay;
    var directionsService;
    var map;

    function initMap() {

      map = new google.maps.Map(document.getElementById('map'), {
         center: {lat: 52.5060713, lng: 13.3962265},
         zoom: 11
      });

      <% @locations.each do |location| %>
        new google.maps.Marker({
            map: map,
            position: {lat: <%= location.lat %>, lng: <%= location.long %>},
            title: '<%= location.name %>' });
      <% end %>



     navigator.geolocation.getCurrentPosition(calcRoute);



    function calcRoute(position) {

      directionsDisplay = new google.maps.DirectionsRenderer();
      directionsService = new google.maps.DirectionsService();

      var start = {lat: position.coords.latitude, lng: position.coords.longitude};
     var end = {lat: 52.5376581, lng: 13.3496172};
    //  getElementById('end').value
      //var end =


      var request = {
        origin:start,
        destination:end,
        travelMode: google.maps.TravelMode.TRANSIT
      };

      directionsDisplay.setMap(map);

      directionsService.route(request, function(result, status) {
        //console.log(directionsDisplay);
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(result);
        }
      });
    }
  }
  </script>

   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_viYAPxX0PcTdcTS6ep58Ot9ZtgYsqNU&callback=initMap"
   async defer></script>

</body>
</html>


trnsl.1.1.20160604T202707Z.a73ee0646caf8312.83365257555d9bb2753c6850a8a306c6cc164f42

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @location.long %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/welcome/show.html.erb
<h1>i am a show</h1>
<h1>Hello <%=@text_to_show %> </h1>